### PR TITLE
Location metadata

### PR DESCRIPTION
**Pull request by SpudGunMan**
messed up my forks this is adding meta data

### CODE REVIEW

**Comment by mbridak** [comment]
Thanks for the PR.

You should take a look at augratin. It's what i made after this.

**Comment by SpudGunMan** [comment]
Hey that is fancy! Nice project!

**Comment by SpudGunMan** [comment]
Can’t get the other client to load web engine symbols errors 
Sigh


Excuse typos and brevity, sent from a mobile device.


On Thursday, April 11, 2024, 6:45 PM, Kelly Keeton ***@***.***> wrote:

Hey that is fancy! Nice project! 

On Apr 11, 2024, at 6:33 PM, Michael Bridak ***@***.***> wrote:


Thanks for the PR.

You should take a look at augratin. It's what i made after this.

**Comment by mbridak** [comment]
It's been awhile since it has gotten any development time. Kind of consumed with not1mm to do other projects.
But it could use a port to Qt6.

**Comment by SpudGunMan** [comment]
Fun, I did virtualenv load it fine, not sure why the issue
 The little classic spotter widget is nice and is small footprint used it activating today worked well!
K


Excuse typos and brevity, sent from a mobile device.


On Friday, April 12, 2024, 8:53 PM, Michael Bridak ***@***.***> wrote:




It's been awhile since it has gotten any development time. Kind of consumed with not1mm to do other projects.
But it could use a port to Qt6.

**Pull request merged**
