### PR TITLE
fix FT* mode

### PR DESCRIPTION
**Pull request by SpudGunMan**
the report is inverse

### CODE REVIEW

**Comment by mbridak** [comment]
What's this one doing?

**Comment by SpudGunMan** [comment]
Before the patch when selecting ft* it removes all FT* from the list 

Is it not the same for you?

**Comment by mbridak** [comment]
Yes, it was the desired effect. ;-)
I'm not big on FT* and wanted to filter it out.
Feel free to add a +FT*. but I'd like to keep the -FT*

**Comment by SpudGunMan** [comment]
It didn't occur to me it was a negate FT8 


The if statement makes a lot more sense now haha 

RRR

**Pull request closed without merging**
